
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Provider } from 'react-redux'
import store from "./redux/store";
import Providers from "./Providers";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  width: "device-width",
  initialScale: 1.0,};

export default function RootLayout({ children }) {
  return (
     
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white w-full min-h-screen`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  
  );
}
